version: 2.1

workflows:
  workflow:
    jobs:
      - go-test

jobs:
  go-test:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - run: make build
      - run: make test
      - run: make self-coverage
